fname = input('Your First name: ')
lname = input('Your Last name: ')
age = input('How old are you: ')
location = input('Where do you live: ')
print ('Your First name is: ' + fname + ' Your Last name is: ' + lname + ' Your age is: ' + age + ' You live in: ' + location)
